spring.application.name=document-service
spring.datasource.url=jdbc:postgresql://localhost:5432/medical_knowledge_assistant
spring.datasource.username=mka
spring.datasource.password=mka

server.port=8081